[package]
name = "bin"
version = "0.1.0"
authors = ["kurt <kurtlawrence92@gmail.com>"]
edition = "2021"

[[bin]]
path = "main.rs"
name = "ogma"

[dependencies]
# workspace
libs = { path = "../libs" }
ogma = { path = "../ogma" }
ogma-shell = { path = "../ogma-shell" }

# crates.io
clap = { version = "3", features = [ "derive" ] }
glob = "0.3"
