[workspace]
members = [ "ogma", "ogma-ls", "ogma-shell", "libs", "bin" ]
default-members = ["ogma", "libs", "bin"]

[profile.release]
lto = true
codegen-units = 1

[profile.bench]
debug = 2 # Turn on for profiling benching
