name: Publish

on:
  push:
    tags: '*'

jobs:
  publish-windows:
    name: Publish Assets
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "Cargo.toml"
        token: ${{ secrets.GITHUB_TOKEN }}
