name: Publish

on:
  push:
    tags: '*'

jobs:
  linux:
    name: Build Linux
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create output directory
      run: mkdir output

    - name: Copy files to output
      run: |
        cp Cargo.toml output/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: output/*

  windows:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create output directory
      run: mkdir output

    - name: Copy files to output
      run: |
        cp bin\main.rs output\

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: output\*

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs:
      - linux
      - windows

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create output directory
      run: mkdir output

    - name: Download Linux Artifacts
      uses: actions/download-artifact@v2
      with:
        name: linux
        path: output
    
    - name: Download Windows Artifacts
      uses: actions/download-artifact@v2
      with:
        name: windows
        path: output
    
    - name: Create Release
      with:
        artifacts: "output/*"
        token: ${{ secrets.GITHUB_TOKEN }}
